### ISSUE TITLE
Error when saving GP quantities in kernel_and_predictive.py

### ISSUE THREAD

**Issue by jules-samaran** [team-approx-bayes/dnn2gp#1]
Dear authors,

Thank you for making this code available, I have been reading your paper with great interest and it is great to be able to reproduce your results. There's one small error that I noticed, running `kernel_and_predictive.py` computes and saves some dnn2gp quantities that are then plotted by running `kernel_and_predictive_plots.py` however the names of the files saved when doing the first run are not the same as the ones used to load the quantities to plot in the second run. 
For example, `kernel_and_predictive.py` saves 'results/CIFAR_Laplace_predictive_var_f.npy' whereas `kernel_and_predictive_plots.py` loads 'results/CIFAR_Laplace_gp_functional_var.npy' .

**Comment by aleximmer** [comment]
Thank you for pointing out this error. We will fix it ASAP.
